/* automatically generated by configure - do not edit */

void sha1_constructor(void);
void rmd160_constructor(void);
void md5_constructor(void);

void
cipher_modules_constructor(void)
{
    static int done = 0;
    if( done )
        return;
    done = 1;

   sha1_constructor();
   rmd160_constructor();
   md5_constructor();
}
